### ISSUE TITLE
what to do with the end caps not aligning

### ISSUE THREAD

**Issue by argyleink** [CSS-Next/logo.css#14]
some people think it's glaringly bad, some dont notice, some will never see it at the tiny size they'll usually see it, other's might print it on a poster and be appalled. a couple questions:

- if we solve it, then we cant just point to the Dinish font
- if we solve it, how will we distribute the glyphs/shapes

**Comment by romainmenke** [comment]
Upstream issue?
Maybe the Dinish font creators are open to making such changes?

**Comment by mxdvl** [comment]
While visual adjustments make sense for a font, which is visually adjusted to work best at typical reading sizes, for a word mark that is often drawn at large “display” sizes, following [a more rigorously geometric solution](https://svelte.dev/playground/b95d70159b2f4d9e962fd0eb0c45c060?version=5.1.15) may be preferable.

Obviously in this case the canonical version would be the SVG and distributed that way.

**Comment by chriskirknielsen** [comment]
Agreeing with @mxdvl here — this was the one thing that bothered me using Dinish that I [had to fix](https://github.com/CSS-Next/css-next/issues/105#issuecomment-2365339705) (though it is only following in the footsteps of original DIN fonts 😄).

While I think it's very cool to be able to recreate this in CSS with very little code, it does also mean it might look a little different based on the browser (font metrics are not always consistent across browsers) or if the fontr fails to load, and as such, two things come to mind:
- it's okay to recreate the logo with the font as-is; it's a detail that can be ignored if you want to play around with it.
- a "source of truth" SVG version would make sense: it is a logo after all, and as such I expect it to be used a lot more as SVG (or PNG) than an embedded HTML/CSS block of code, which means that the typeface changes can be baked into that "true" logo.

Providing SVG versions means that folks who would like to style if still can do so with CSS, meaning you could add, for example, the version number with a live piece of text using Dinish, but with a "imposed" set of paths for the CSS letters. Anyways I'm basically just repeating Max's point here!

If keeping it as editable text is essential, then I like the idea proposed by @romainmenke — it would be fairly easy to add either an alternate glyph, or a ligature, to correct this issue, but of course, that would require the proper CSS to be enabled so you still get the problem with very basic styling, so the fork might be the way to go in this case?

**Comment by Crissov** [comment]
Works for me, but better ask @chriskirknielsen for instance.

**Comment by rol4nd909** [comment]
@itsjavi or @argyleink can one of you update the figma file with the latest font?

https://github.com/playbeing/dinish/releases/tag/v4.003 the caps are aligned now

**Comment by argyleink** [comment]
> @itsjavi or @argyleink can one of you update the figma file with the latest font?
> 
> https://github.com/playbeing/dinish/releases/tag/v4.003 the caps are aligned now.
> 
> I opend a pull request #55 with the new svg using the new font

done!
