### ISSUE TITLE
Square variant?

### ISSUE THREAD

**Issue by romainmenke** [CSS-Next/logo.css#15]
To avoid the logo looking kinda weird when the display location has own rounded corners: 
<img width="754" alt="Screenshot 2024-11-12 at 23 40 03" src="https://github.com/user-attachments/assets/22c0af9e-1d90-4e0e-a92f-12ccfd6cc1f9">

**Comment by argyleink** [comment]
def should offer this 👍🏻

**Comment by romainmenke** [comment]
Thank you @argyleink 🙇
