### ISSUE TITLE
Preserve color at export

### ISSUE THREAD

**Issue by Que-tin** [CSS-Next/logo.css#17]
Currently only the `.ico` and `.svg` files have to correct background color it seems like the colors are no preserved on export.

While checking I got the following results:
- .avif #6E319E
- .png / .jpg #6E2F9F
- .webp #6F2FA0

**Comment by argyleink** [comment]
💩 
what did you use to check?

#18 could be related in that maybe it'll provided better colorsafe options for outputting variants
