### ISSUE TITLE
Reproducible steps for generating assets

### ISSUE THREAD

**Issue by mxdvl** [CSS-Next/logo.css#18]
There should be a documented, cross-platform way to generated all the variations of the logo (.ico, .webp, .png, .avif, …).

> [!NOTE]
> For my own website [I use `resvg`, `imagick-wasm` & Deno to generate PNG assets from SVG](https://github.com/mxdvl/mxdvl/blob/0ae1d4a5def21a4dbf1f0a0401ee1442cdf4ab04/deno/scripts/process_icons.ts#L36),
> have [used bash scripts with `vips` & Image Magick’s `convert` previously](https://github.com/mxdvl/mxdvl/blob/main/cmps/generate-favicon.sh),
> and would be happy to raise a PR proposal to this end.

Resolved by #22

**Comment by argyleink** [comment]
as mentioned in #17, there appears to be some color value loss in conversion. @mxdvl, if you're down to test, want to see if the conversions from image magick / sharp / squoosh cli can get us what we need? get 2 birds one stone: reproducible assets & fine grained control so colors arent transformed
