### ISSUE TITLE
Apply for the special usage at Simple Icons

### ISSUE THREAD

**Issue by LitoMore** [CSS-Next/logo.css#23]
Hi, I'm the maintainer of the https://github.com/simple-icons/simple-icons project. We're the provider of the https://shields.io project.

According to the [Logo Usage Guidelines](https://github.com/CSS-Next/logo.css#logo-usage-guidelines) section, the logo background is filled with `#663399` and white `CSS` text.

But our project only supports single-path SVG. Which means the `CSS` will be transparent. I've created a pull request at https://github.com/simple-icons/simple-icons/pull/12134. Is this OK for your team?

Please let me know your thoughts.

Thanks.

**Comment by argyleink** [comment]
thanks so much for asking! 

i think it's very acceptable for y'all to adapt it to your design system in this way.

**Comment by Que-tin** [comment]
Hey @LitoMore,

is there anything else we can help you with or can I close the issue?

**Comment by LitoMore** [comment]
Thank you all. Closing as done.
