### ISSUE TITLE
Add accessibility attributes and tags

### ISSUE THREAD

**Issue by alvaromontoro** [CSS-Next/logo.css#37]
The SVG files could get an accessibility boost by adding some attributes:

- Image aria role (`role="img"`)
- Linked descriptions (`aria-labelledby="[IDs]"`)
- Title (`<title>`)
- Description (`<desc>`)

Sources:
- [Creating Accessible SVGs, by Carie Fisher at Deque](https://www.deque.com/blog/creating-accessible-svgs/)
- [Accessible SVGs: Perfect Patterns For Screen Reader Users, by Carie Fisher at Smashing Magazine](https://www.smashingmagazine.com/2021/05/accessible-svg-patterns-comparison/)

**Comment by argyleink** [comment]
fixed by #36
