### ISSUE TITLE
24px outline icon

### ISSUE THREAD

**Issue by Kilian** [CSS-Next/logo.css#38]
I needed a 24px outline icon (in the style of the popular Tabler icon set) so I made one, might be useful for others:

![css-outline](https://github.com/user-attachments/assets/e3e7e8e9-4251-4dfa-b0be-b63ece7d392e)

Could be the basis for a favicon or other icon sets. The accompanying Tabler Icons issue is located here: https://github.com/tabler/tabler-icons/issues/1266

**Comment by argyleink** [comment]
the use case is great, but we're going to close this and leave variants like this one to [user land](https://github.com/CSS-Next/logo.css?tab=readme-ov-file#modifications).
