### ISSUE TITLE
Fix curve in letter C?

### ISSUE THREAD

**Issue by alvaromontoro** [CSS-Next/logo.css#46]
I cannot be the only one that sees this.

![Detail of the letter C, showing that the line dwindles and curves](https://github.com/user-attachments/assets/4bebea89-725c-4306-a463-970a4fefc39d)

![Zoom into the letter C, to show better how the line dwindles and curves, with arrows pointing at the problematic areas](https://github.com/user-attachments/assets/71bac1e1-324c-4a77-b67f-d8f37a8c7272)

Looking at the font, this seems like something that may have happened when converting the text into path. The notch has been there since the beginning, and it has changed slightly as the paths were updated. (I know it's small, but it feels weird 😳)

**Comment by rol4nd909** [comment]
Thanks gonna fix it
