### ISSUE TITLE
Artifacts in Chrome

### ISSUE THREAD

**Issue by syncopated** [CSS-Next/logo.css#48]
First off, I want to say thanks to all involved! 🙏 Love this initiative and the logo 💜 

This could just be me but when viewing the logo with Chrome on an external monitor I am seeing some visual artifacts. It looks fine on a retina/higher pixel density screen. With Firefox and Safari it looks great. Not sure if this might just be me or my screen (It is a Dell U3415W in case that helps) 🤔 

![Screenshot 2024-11-22 at 9 10 34 AM](https://github.com/user-attachments/assets/5f634303-4b2a-4281-83ea-cec20c54b724)

**Comment by rol4nd909** [comment]
Hi thanks for pointing this out, I'm not able to test this my self but could you try to add the following to the svg and check if it makes a difference?

`style="shape-rendering: crispEdges;"`

Thanks in advance

**Comment by syncopated** [comment]
Thanks for taking a look at this @rol4nd909! I tried out `crispEdges` and some other values for `shape-rendering` and that made it worse.

**Comment by rol4nd909** [comment]
Hmm thanks for checking, to bad it only makes it worse :( I hope someone else have an idea.

**Comment by Schepp** [comment]
It may have to do with GPU accelerated rendering, or the lack of it. When you open `chrome://gpu/`, is `Rasterization` `Hardware accelerated` or not? If yes, does it get any better if you open `chrome://flags/` search for `GPU rasterization` and set it to `disabled`?

**Comment by meyerweb** [comment]
> It may have to do with GPU accelerated rendering, or the lack of it. When you open `chrome://gpu/`, is `Rasterization` `Hardware accelerated` or not? If yes, does it get any better if you open `chrome://flags/` search for `GPU rasterization` and set it to `disabled`?

I saw something very similar (not pixel-for-pixel the same, but visibly jaggier on an external monitor nonetheless) on the latest public Chrome/macOS, and taking these steps seems to have cleared up the jags.

**Comment by syncopated** [comment]
Thanks @meyerweb and @Schepp. Rasterization _was_ hardware accelerated initially and disabling it does seem to reduce the jags for me as well 🙏

**Comment by Schepp** [comment]
Glad we found the reason! But on the long term it would be better to have GPU acceleration re-enabled for the sake of performance and power consumption. Maybe it's a temporary problem with current Chrome with that specific configuration and hopefully it gets fixed. I would therefore set an alarm and revisit the topic in a few Chrome versions to check if you can roll back your browser settings.

**Comment by Que-tin** [comment]
It seems like I can close the issue for now 😊
