### ISSUE TITLE
Attribution for MIT License?

### ISSUE THREAD

**Issue by blueset** [CSS-Next/logo.css#49]
Hi, I’m looking to use the new CSS logo in my project, and I saw the README file mentioned that the design is licensed under the MIT license. However, I didn’t see a copy of the MIT license in the repository.

How should I attribute the logo (i.e. the “Copyright (c) [year] [fullname]” line from the MIT license) in my project?

**Comment by rol4nd909** [comment]
Hi thanks for point this out, we just added a license as you can [see here](https://github.com/CSS-Next/logo.css?tab=CC0-1.0-1-ov-file)
