### ISSUE TITLE
Increase legibility for 16x16 version

### ISSUE THREAD

**Issue by Que-tin** [CSS-Next/logo.css#50]
As mentioned in the [CSSWG-Drafts Issue](https://github.com/w3c/csswg-drafts/issues/11193) the current logo scaled diwb ti 16x16 is only barely readable.

In order to use it as a favicon the icon needs to me "responsive" in a way that the font needs to take on more space on for logos. We also need to add a sentence or two to make sure this logo isn't used as alternative logo.

Question:
Do we want to embed such responsivity into the SVG-Code? We need to provide other image formats anyway and those obviously won't behave responsive, but instead need to be generated once.

**Comment by rol4nd909** [comment]
I think to make the SVG responsive so at really small size the text is still readable would be a perfect solution. I'll try to make an example.
