### ISSUE TITLE
Proposal for new logo design

### ISSUE THREAD

**Issue by MaxPScript** [CSS-Next/logo.css#51]
Hello everyone!
I would like to propose my design for the CSS logo.
The current logo is excellent; it captures both simplicity and completeness. It even inspired my project!
Discover more details [here](https://github.com/MaxPScript/LogoCSS/tree/main), please!

**Comment by Que-tin** [comment]
Hey @MaxPScript,

interesting idea unfortunately you are a bit late. The discussion on the new logo design and the origin to this repository already happened a while back in [this issue](https://github.com/CSS-Next/css-next/issues/105). We hope that you still like the new logo.

**Comment by MaxPScript** [comment]
'a bit late'... No! I'm just a bit early. When the time comes for a CSS redesign again, everything will already be prepared... For now, my cherished gothic will remain quietly in the corner, draped in a marble veil, unhurried and simply existing. Oh My Gothic! You are too beautiful for the spotlight... All the best.
